### ISSUE TITLE
Incorrect topic for this repo?

### ISSUE THREAD

**Issue by pafnuty** [Roboe/userscripts#3]
Hi @Roboe!
I found link to this repo on page https://github.com/topics/dle and, I suppose, `dle` topic here means something else, not DataLife Engine CMS?

**Comment by Roboe** [comment]
Hi, @pafnuty!

DLE means "Diccionario de la lengua española" ("Spanish Language Dictionary"), which is the dictionary made by the "Real Academia Española" ("Royal Spanish Academy", the official language authority in Spain) with other Spanish authorities worldwide. So no, nothing to do with a CMS, sorry.

I wrote those topics when the feature in GitHub was released. I guess it was a little inmature feature then, and it was used as if they were hashtags. I think you are right, that the topics associated with this repo are incorrect because they don't have nothing to do with tech-related "topics." I'll change them.

Thanks for reporting!
